Models/Provider.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgilerapProcessSystems.Models
{
    public partial class Provider
    {
        public int ID { get; set; }
        public int? WorkID { get; set; }
        public int? UserID { get; set; }
        public int? CreateByID { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime? CreateDate { get; set; }
        public int? UpdateByID { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime? UpdateDate { get; set; }
        public bool IsDelete { get; set; }

        [ForeignKey("CreateByID")]
        public virtual User CreateBy { get; set; }
        [ForeignKey("UpdateByID")]
        public virtual User UpdateBy { get; set; }
        public virtual Work Work { get; set; }
        [ForeignKey("UserID")]
        public virtual User User { get; set; }

    }
}

Models/Work.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgilerapProcessSystems.Models
{
    public partial class Work
    {
        public int ID { get; set; }
        public int? HeaderID { get; set; }
        public string? Project { get; set; }
        public string? Name { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DueDate { get; set; }
        public int? StatusID { get; set; }
        public string? Remark { get; set; }
        public int? CreateByID { get; set; }
        [DataType(DataType.Date)]
        public DateTime? CreateDate { get; set; }
        public int? UpdateByID { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime? UpdateDate { get; set; }
        public bool IsDeleted { get; set; }

        [ForeignKey("CreateByID")]
        public virtual User CreateBy { get; set; }
        [ForeignKey("UpdateByID")]
        public virtual User UpdateBy { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<WorkLog> WorkLog { get; set; }
        public virtual ICollection<Provider> Provider { get; set; }

    }
}

Controllers/WorkController.cs
using AgilerapProcessSystems.Common;
using AgilerapProcessSystems.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace AgilerapProcessSystems.Controllers
{
    public class WorkController : Controller
    {

        private Agile_Process_SystemsContext db = new Agile_Process_SystemsContext();
        private static List<SelectListItem> _StatusDropdownList = new List<SelectListItem>();
        private static List<SelectListItem> _UserDropdownList = new List<SelectListItem>();

        public async Task<IActionResult> Index()
        {
            //! Get SessionUser
            User? user = await GetSessionUser();

            //! If User Null return to Login
            if (user == null) return RedirectToAction("Login", "Home");

            ViewBag.UserName = user.Name;
            var workDBList = await GetDBWork();
            return View(workDBList);

        }

        public async Task<IActionResult> Create()
        {
            ClearStatic();
            await InitStatic();

            //! Get SessionUser
            User? user = await GetSessionUser();
            //! If User Null return to Login
            if (user == null) return RedirectToAction("Login", "Home");

            var workDBList = await GetDBWork();
            Work work = new Work() { IsDeleted = false, CreateDate = DateTime.Now, CreateByID = user.ID, UpdateByID = user.ID };
            workDBList.Add(work);
            ViewbagData();
            return View(workDBList.Where(s => s.IsDeleted == false));
        }

        [HttpPost]
        public async Task<IActionResult> Create(Work work)
        {
            Status statusDefault = await db.Status.Where(s => s.StatusName == work.statusDefaultNoDueDate).FirstOrDefaultAsync();
            work.Provider = new List<Provider>();

            if (work.DueDate == null)
            {
                work.StatusID = statusDefault.ID;
            }

            if (work.StatusID == statusDefault.ID && work.DueDate != null)
            {
                Status status2Default = await db.Status.Where(s => s.StatusName == work.statusDefaultWithDueDate).FirstOrDefaultAsync();
                work.StatusID = status2Default.ID;
            }

            bool hasProvider = false;
            if (work.GroupProvider != null || work.IsSelectedAll)
            {
                hasProvider = true;
            }
            if (hasProvider)
            {
                if (work.IsSelectedAll)
                {
                    foreach (var i in await db.User.ToListAsync())
                    {
                        Provider provider = new Provider()
                        {
                            CreateByID = work.CreateByID, //! Change later for user login
                            UpdateByID = work.UpdateByID,
                            CreateDate = DateTime.Now,
                            UpdateDate = DateTime.Now,
                            IsDelete = false,
                            UserID = i.ID
                        };
                        work.Provider.Add(provider);
                        db.Provider.Add(provider);
                    }
                }
                else
                {
                    List<string> providerIDList = work.GroupProvider.Split(',').ToList();
                    foreach (var i in providerIDList)
                    {
                        if (Int32.TryParse(i, out int id))
                        {
                            Provider provider = new Provider()
                            {
                                CreateByID = work.CreateByID,
                                UpdateByID = work.UpdateByID,
                                CreateDate = DateTime.Now,
                                UpdateDate = DateTime.Now,
                                IsDelete = false,
                                UserID = id
                            };
                            db.Provider.Add(provider);
                            work.Provider.Add(provider);
                        }
                    }
                }
            }

            WorkLog workLog = new WorkLog()
            {
                No = 1,
                Project = work.Project,
                Name = work.Name,
                DueDate = work.DueDate,
                StatusID = work.StatusID,
                Remark = work.Remark,
                CreateByID = work.CreateByID,
                UpdateByID = work.UpdateByID,
                CreateDate = DateTime.Now,
                UpdateDate = DateTime.Now,
                IsDelete = false
            };
            workLog.ProviderLog = new List<ProviderLog>();
            work.WorkLog = new List<WorkLog>()
            {
                workLog
            };
            foreach (var i in work.Provider)
            {
                ProviderLog providerLog = new ProviderLog()
                {
                    UserID = i.UserID,
                    CreateByID = i.CreateByID,
                    UpdateByID = i.UpdateByID,
                    CreateDate = DateTime.Now,
                    UpdateDate = DateTime.Now,
                    IsDelete = false
                };
                workLog.ProviderLog.Add(providerLog);
                db.ProviderLog.Add(providerLog);
            }
            db.Work.Add(work);
            db.WorkLog.Add(workLog);
            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException e)
            {
                Console.WriteLine(e);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            //! Get SessionUser
            User? user = await GetSessionUser();
            //! If User Null return to Login
            if (user == null) return RedirectToAction("Login", "Home");

            ClearStatic();
            await InitStatic();
            if (id == null)
            {
                return NotFound();
            }
            var workDBList = await GetDBWork();

            var workEditItem = workDBList.Where(s => s.ID == id).First();

            //! UpdateByID to current User that Editing
            workEditItem.UpdateByID = user.ID;

            ViewBag.EditID = id;

            if (workEditItem.Provider != null)
            {
                foreach (var i in workEditItem.Provider.Where(s => s.IsDelete == false))
                {
                    foreach (var j in _UserDropdownList)
                    {
                        if (i.UserID.ToString() == j.Value)
                        {
                            j.Selected = true;
                            continue;
                        }
                    }
                }
            }

            ViewbagData();
            return View(workDBList);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Work work)
        {
            bool hasModifyProvider = false;
            if (work.GroupProvider != null || work.IsSelectedAll)
            {
                hasModifyProvider = true;
            }
            if (hasModifyProvider)
            {
                if (work.IsSelectedAll)
                {
                    work.GroupProvider = "";
                    var userDBList = await db.User.ToListAsync();
                    foreach (var j in userDBList)
                    {
                        if (j == userDBList.Last())
                        {
                            work.GroupProvider += j.ID;
                        }
                        else
                        {
                            work.GroupProvider += j.ID + ",";
                        }
                    }
                }
                List<string> providerIDList = work.GroupProvider.Split(',').ToList();
                foreach (var j in work.Provider)
                {
                    bool isExist = false;
                    foreach (var i in providerIDList)
                    {
                        if (Int32.TryParse(i, out int id))
                        {
                            if (j.UserID == id)
                            {
                                isExist = true;
                                if (j.IsDelete)
                                {
                                    db.Entry(j).State = EntityState.Modified;
                                    j.UpdateDate = DateTime.Now;
                                    j.IsDelete = false;
                                }
                                providerIDList.Remove(i);
                                break;
                            }
                        }
                    }

                    if (isExist == false)
                    {
                        db.Entry(j).State = EntityState.Modified;
                        j.IsDelete = true;
                        j.UpdateDate = DateTime.Now;
                    }
                }

                if (providerIDList.Count > 0)
                {
                    foreach (var i in providerIDList)
                    {
                        if (Int32.TryParse(i, out int id))
                        {
                            Provider provider = new Provider()
                            {
                                CreateByID = work.UpdateByID,
                                UpdateByID = work.UpdateByID,
                                CreateDate = DateTime.Now,
                                UpdateDate = DateTime.Now,
                                IsDelete = false,
                                UserID = id
                            };
                            db.Provider.Add(provider);
                            work.Provider.Add(provider);
                        }

Views/Shared/EditorTemplates/Provider.cshtml
@model Provider

@Html.HiddenFor(m => m.ID)
@Html.HiddenFor(m => m.WorkID)
@Html.HiddenFor(m => m.UserID)
@Html.HiddenFor(m => m.CreateDate)
@Html.HiddenFor(m => m.IsDelete)
@Html.HiddenFor(m => m.CreateByID)
@Html.HiddenFor(m => m.UpdateByID)

Views/Shared/EditorTemplates/Work.cshtml
@model Work

@{
    List<SelectListItem> stautsDropdownList = ViewBag.StautsDropdownList;
    List<SelectListItem> userDropdownList = ViewBag.UserDropdownList;
}

@Html.HiddenFor(m => m.ID)
@Html.HiddenFor(m => m.IsDeleted)
@Html.HiddenFor(m => m.IsSelectedAll)
@Html.HiddenFor(m => m.GroupProvider)
@Html.HiddenFor(m => m.CreateDate)
@Html.HiddenFor(m => m.UpdateDate)
@Html.HiddenFor(m => m.CreateByID)
@Html.HiddenFor(m => m.UpdateByID)

<script>
    document.addEventListener("DOMContentLoaded",
        () => {
            $('#select-tops-options').multiselect({
                buttonClass: 'form-select',
                nonSelectedText: 'Select Provider',
                buttonContainer: '<div class="btn-danger" id="select-tops-options-container"></div>',
                selectedClass: 'active multiselect-selected',
                numberDisplayed: 5,
                buttonWidth: '18em',
                includeSelectAllOption: true,
                onSelectAll: function (options) {
                    document.getElementById("work_IsSelectedAll").value = true;
                },
                onDeselectAll: function (options) {
                    document.getElementById("work_IsSelectedAll").value = false;
                },
                //includeResetOption: true,
                //selectAllName: 'select-all-name',
                onChange: function (option, checked) {
                    /*
                     * Not there yet
                     */
                    if (checked) {
                        document.querySelectorAll(`[value="${$(option[0])[0].value}"]`)[1].ariaChecked = "true";
                        document.querySelectorAll(`[value="${$(option[0])[0].value}"]`)[0].ariaChecked = "true";
                    } else {
                        document.querySelectorAll(`[value="${$(option[0])[0].value}"]`)[1].ariaChecked = "false";
                        document.querySelectorAll(`[value="${$(option[0])[0].value}"]`)[0].ariaChecked = "false";
                    }

                    //$("#select-tops-options").multiselect('deselect', '1');
                    var toppings = $('#select-tops-options option:selected');

                    var selected = [];
                    $(toppings).each(function (index, item) {
                        selected.push([$(this).val()]);
                    });

                    document.getElementById("work_GroupProvider").value = selected.join(',');
                },
                templates: {
                    button:
                        '<button type="button" class="multiselect dropdown-toggle" ' +
                        'data-bs-toggle="dropdown"><span class="multiselect-selected-text"></span></button>',
                    resetButton: '<div class="multiselect-reset text-center p-2"><button type="button" class="btn btn-sm btn-danger"></button></div>'
                }
            });

        });
</script>
<div>
    @Html.EditorFor(m => m.Provider)
</div>
<tr>
    <td>
        @Html.EditorFor(m => m.CreateDate)
    </td>
    <td>
        <input type="text" asp-for="Project" class="form-control" />
    </td>
    <td>
        <input type="text" asp-for="Name" class="form-control" />
    </td>
    <td>
        @Html.EditorFor(m => m.DueDate)
    </td>
    <td>
        @Html.DropDownListFor(m => m.CreateByID, userDropdownList, new {disabled = "disabled" })
    </td>
    <td>
        <select id="select-tops-options" required asp-items="userDropdownList" multiple="multiple">
        </select>
    </td>
    <td>
        @Html.DropDownListFor(m => m.StatusID, stautsDropdownList, new { })
    </td>
    <td>
        <input type="text" asp-for="Remark" class="form-control" />
    </td>
    <td>
        <input type="submit" value="Submit" class="btn-success" /><br />
        <input asp-action="Index" asp-controller="Work" type="submit" value="Cancel" class="btn-danger" />
    </td>
</tr>